[package]
name = "rustips-calculator"
version = "0.1.0"
authors = ["Valentin Famelart <valentin.famelart@invenis.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
